In [1]:
import numpy as np

In [2]:
def pred(w, X):
    return np.sign(np.dot(w.T, X))

def has_converged(X, y, w):
    return np.array_equal(pred(w, X), y)

In [13]:
def my_perceptron(X, y, w_init):
    w = [w_init]
    N = X.shape[1]
    d = X.shape[0]
    mis_points = []
    while True:
        # mix data
        mix_id = np.random.permutation(N)
        for idx in mix_id:
            xi = X[:, idx].reshape(d, 1)
            yi = y[0, idx]
            if pred(w[-1], xi)[0] != yi:
                mis_points.append(idx)
                w_new = w[-1] + yi*xi
                w.append(w_new)
        if has_converged(X, y, w[-1]):
            break
    return (w, mis_points)

In [14]:
means = [[2, 2], [4, 2]]
cov = [[.3, .2], [.2, .3]]
N = 10
X0 = np.random.multivariate_normal(means[0], cov, N).T
X1 = np.random.multivariate_normal(means[1], cov, N).T

X = np.concatenate((X0, X1), axis = 1)
y = np.concatenate((np.ones((1, N)), -1*np.ones((1, N))), axis = 1)
# Xbar 
Xbar = np.concatenate((np.ones((1, 2*N)), X), axis = 0)

print(Xbar.T)
print(y)

d = Xbar.shape[0]
w_init = np.random.randn(d, 1)
(w, m) = my_perceptron(Xbar, y, w_init)
print(w[-1].T)
# print(len(w[-1]))

[[1.         2.02047255 2.57275292]
 [1.         2.36956362 1.56203014]
 [1.         1.20625954 1.04452122]
 [1.         2.35853286 2.37141223]
 [1.         1.67541566 2.45288313]
 [1.         2.30636447 2.16765377]
 [1.         1.59605683 2.71853328]
 [1.         2.40204518 2.60115365]
 [1.         2.10201917 1.7889657 ]
 [1.         2.42780885 2.72659206]
 [1.         4.09822022 2.06608103]
 [1.         3.34665125 1.78145207]
 [1.         4.07895638 1.95316864]
 [1.         4.12644714 1.61728091]
 [1.         3.4058985  1.48072912]
 [1.         4.85537154 3.02371418]
 [1.         4.76519682 1.96569318]
 [1.         4.21783046 2.55011789]
 [1.         3.64220876 2.00266213]
 [1.         3.76305322 1.5410247 ]]
[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1. -1. -1. -1. -1. -1. -1. -1. -1.
  -1. -1.]]
[[ 2.5113337  -3.99346324  4.72597025]]
